services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s



  table-service:
    build:
      context: ./table-service
      dockerfile: Dockerfile
    image: table-image
    container_name: table-container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  spring-cloud-gateway:
    build:
      context: ./spring-cloud-gateway
      dockerfile: Dockerfile
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8082:8082"
    networks:
      - backend

  menu-service:
    build:
      context: ./menu-service
      dockerfile: Dockerfile
    image: menu-image
    container_name: menu-container
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
