version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend
    profiles: ["active"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  table-service:
    build:
      context: ./table-service
      dockerfile: Dockerfile
    image: table-image
    container_name: table-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend
    profiles: ["active"]

  menu-service:
    build:
      context: ./menu-service
      dockerfile: Dockerfile
    image: menu-image
    container_name: menu-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - backend
    profiles: ["deactive"]

networks:
  backend:
