name: CI for table-service with MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build table-service using Maven (skip tests)
        run: mvn clean package -DskipTests --file table-service/pom.xml

      - name: Build menu-service using Maven (skip tests)
        run: mvn clean package -DskipTests --file menu-service/pom.xml

      - name: Start MySQL and table-service with Docker Compose
        run: docker compose up --build

      - name: Shutdown containers
        if: always()
        run: docker compose down