name: CI with DB-dependent tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start MySQL and table-service with Docker Compose
        run: docker compose --profile active up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql-container mysqladmin ping -h"localhost" --silent; do
            sleep 2
          done

      - name: Run tests (integration + unit)
        run: mvn clean test --file table-service/pom.xml

      - name: Shutdown containers
        if: always()
        run: docker compose down